config/routes.rb
Gonsanchezs::Application.routes.draw do
  root 'static_pages#index'
  get 'cities', to: 'static_pages#cities'
  get 'books', to: 'static_pages#books'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>@gonsanchezs – Marketer, maker.</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <link href="https://fonts.googleapis.com/css?family=Pacifico|Roboto:400,700" rel="stylesheet">
  <link href="https://afeld.github.io/emoji-css/emoji.css" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Roboto+Mono:400,700|Roboto+Slab:400,700|Roboto:400,700" rel="stylesheet">
  <link href="https://file.myfontastic.com/n6vo44Re5QaWo8oCKShBs7/icons.css" rel="stylesheet">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.ico' %>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
</head>
<body>

<div class="wrapper">

<!--

  <nav class="navbar top-nav navbar-default">
    <div class="container-fluid">

      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand glyphicon glyphicon-ice-lolly-tasted" href="#"></a>
      </div>


      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <li><a href="#">Blog</a></li>
          <li><a href="#">Case Studies</a></li>
          <li><a href="#">Contact</a></li>
          <li><a class="socicon-twitter" src="#"></a></li>
          <li><a class="socicon-github" src="#"></a></li>
        </ul>
      </div>
    </div>  

  </nav> 

  -->


<%= yield %>

  <div class="push"></div>
</div>


<div class="footer">
    <p class="footer-text pull-left"><span class="footer-links"><a class="socicon-twitter" id="twitter" href="https://twitter.com/gonsanchezs"></a><a class="socicon-github" id="github" href="https://github.com/gonsanchezs"></a><a class="socicon-medium" id="medium" href="https://m.gonsanchezs.com"></a></span> Made with <i class="em em-rocket"></i> in Reyjkavik</p>
</div>


</body>
</html>

<!--<script>$('body').starfield({ starDensity: 1.0, mouseScale: 1.0 });</script>-->

app/views/static_pages/books.html.erb
<div class="feed">

<p><%= link_to root_path, :class => 'back-link' do %>
  <i class="glyphicon glyphicon-arrow-left"></i> Go to Home
<% end %></p>

<h1 class="list-title">Good books.</h1>
<p class="list-intro">I try to read as much as possible (although sometimes, Netflix gets in the way). Not everything I read is good but if it is, you'll find it here. If a book is <span class="highlight">highlighted</span>, that's because I've enjoyed it a lot.</p>

<br />
<br />
  <div class="col-xs-6">
    <ul>
      <li><span class="highlight">Ego is The Enemy</span></li>
      <li>The Obstacle is The Way</li>
      <li><span class="highlight">Rework</span></li>
      <li>Remote</li>
      <li><span class="highlight">Ready Player One</span></li>
      <li>The Subtle Art of Not Giving a Fuck</li>
      <li>Hooked: Building Habit Forming Products</li>
      <li><span class="highlight">Sapiens</span></li>
      <li>The War of Art</li>
      <li>Bird by Bird</li>
      <li><span class="highlight">Meditations</span></li>
      <li>Gang Leader for a Day</li>
      <li>My Life as an Experiment</li>
      <li>The Year of Living Biblically</li>
      <li>Provenance: How a Con Man and a Forger Rewrote the History of Modern Art</li>
      <li>How To Win Friends & Influence People</li>  
      <li><span class="highlight">The Stand</span></li>
      <li>When The Lion Feeds Saga</li>      
      <li>Salem's Lot</li>
      <li>Lord of The Rings Trilogy</li>  
      <li>Harry Potter Saga</li>  
      <li>Barça: The Making of the Greatest Team in History</li>
    </ul>
  </div>
  <div class="col-xs-6">
    <ul>
      <li>More Money Than God</li>
      <li>We Are All Weird</li>
      <li><span class="highlight">Founders at Work</span></li>
      <li>Predictably Irrational</li>
      <li>Freakonomics</li>
      <li>I'll Go Home Then; It's Warm and It has Chairs</li>
      <li>The Four Hour *</li>
      <li>The 22 Immutable Laws of Marketing</li>
      <li>Jony Ive: The Genius Behind Apple's Greatest Products</li>
      <li>The Hard Thing About Hard Things</li>
      <li>Product Design For the Web</li>
      <li><span class="highlight">Zero to One</span></li>
      <li>Soccernomics</li>
      <li>Trust Me I'm Lying: Confessions of a Media Manipulation</li>
      <li>The Art of Learning: A Journey in the Pursuit of Excellence </li>
      <li>Permission Marketing: Turning Strangers Into Friends And Friends Into Customers </li>
      <li>The Adweek Copywriting Handbook</li>
      <li>Pep Guardiola: Another Way of Winning</li>
      <li>Steal Like an Artist</li>
    </ul>
  </div>
</div>

app/views/static_pages/cities.html.erb
<div class="feed">


<p><%= link_to root_path, :class => 'back-link' do %>
  <i class="glyphicon glyphicon-arrow-left"></i> Go to Home
<% end %></p>
<h1 class="list-title">Great cities.</h1>
<p class="list-intro">These are all the cities I've visited over the years. So far, I'm at 126 and I plan to keep going. I something is highlighted, it's because I've enjoyed it a lot.</p>

<br />
<br />
  <div class="col-xs-6">
    <ul>
      <li>San Francisco</li>
      <li>Honolulu</li>
      <li>Monterey</li>
      <li>San Diego</li>
      <li>Los Angeles</li>
      <li>Pacific Beach</li>
      <li>Santa Barbara</li>
      <li>Las Vegas</li>
      <li>Oakland</li>
      <li>Malibu</li>
      <li>Santa Monica</li>
      <li>Ramona</li>
      <li>Cancun</li>
      <li>Tulum</li>
      <li>Playa del Carmen</li>
      <li>Orlando</li>
      <li>Miami</li>
      <li>Plano</li>
      <li>Chicago</li>
      <li>Cincinnati</li>
      <li>Louisville</li>
      <li>Lexington</li>
      <li>Covington</li>
      <li>New York City</li>
      <li>New Jersey</li>
      <li>Philadelphia</li>
      <li>Washington DC</li>
      <li>Bronxville</li>
      <li>Yonkers</li>
      <li>Boston</li>
      <li>Cambridge</li>
      <li>Salem</li>
      <li>Posadas</li>
      <li>Salta</li>
      <li>Tafi del Valle</li>
      <li>Mendoza</li>
      <li>San Rafael</li>
      <li>Malargüe</li>
      <li>San Juan</li>
      <li>Cipoletti</li>
      <li>San Martin de los Andes</li>
      <li>La Cumbre</li>
      <li>Rio Cuarto</li>
      <li>Stykkisholmur</li>
      <li>Grundarfjörður</li>
      <li>Kirkjufellsfoss</li>
      <li>Arnarstapi</li>
      <li>Hellnar</li>
      <li>Bíldudalur</li>
      <li>Pingeyri</li>
      <li>Ísafjörður</li>
      <li>Suðureyri</li>
      <li>Hanga Roa</li>
      <li>Santiago de Chile</li>
      <li>Bariloche</li>
      <li>Rawson</li>
      <li>Puerto Madryn</li>
      <li>Buenos Aires</li>
      <li>Sunchales</li>
      <li>Rosario</li>
      <li>Victoria</li>
      <li>Fray Bentos</li>
      <li>Gualeguaychú</li>
      <li>General Pico</li>
    </ul>
  </div>
  <div class="col-xs-6">
    <ul>
      <li>La Cumbrecita</li>
      <li>Los Rearts</li>
      <li>Villa General Belgrano</li>
      <li>Nono</li>
      <li>San Javier</li>
      <li>San Clemente</li>
      <li>Carlos Paz</li>
      <li>La Calera</li>
      <li>Santa María de Punilla</li>
      <li>Tanti</li>
      <li>Escobar</li>
      <li>Montevideo</li>
      <li>Colonia</li>
      <li>Punta del Este</li>
      <li>La Paloma</li>
      <li>Punta del Diablo</li>
      <li>El Chuy</li>
      <li>Porto Alegre</li>
      <li>Ferrugem</li>
      <li>Cariló</li>
      <li>Valeria del Mar</li>
      <li>Pinamar</li>
      <li>La Plata</li>
      <li>Miramar</li>
      <li>Ciudad del Cabo</li>
      <li>Madrid</li>
      <li>Barcelona</li>
      <li>Nantes</li>
      <li>Paris</li>
      <li>Poissy</li>
      <li>Clisson</li>
      <li>Pontorson</li>
      <li>Rue-sur-Cuesnon</li>
      <li>Ginebra</li>
      <li>Chandolin</li>
      <li>Sion</li>
      <li>Crans-Montana</li>
      <li>Amsterdam</li>
      <li>Frankfurt</li>
      <li>Venecia</li>
      <li>Ferrara</li>
      <li>Roma</li>
      <li>Pisa</li>
      <li>Florencia</li>
      <li>Lastra</li>
      <li>Lastra a Signa</li> 
      <li>Volterra</li>
      <li>San Gimignano</li>
      <li>Radda in Chianti</li>
      <li>Volpaia</li>
      <li>Panzano in Chianti</li>
      <li>Greve in Chianti</li>
      <li>Stockholm</li>
      <li>Bergen</li>
      <li>Oslo</li>
      <li>Flåm</li>
      <li>Aurland</li>
      <li>Voss</li>
      <li>Reyjkavik</li>
      <li>Vik í Myrdal</li>
      <li>Akureyri</li>
      <li>Reykjahlíð</li>
      <li>Þingvellir</li>
    </ul>
  </div>
</div>

app/views/static_pages/index.html.erb
<div class="feed">
  <h1 class="title">Hola, che.<br /> I’m a <span class="skills">marketer</span>.</h1>
    <br />
  <p>Argentinean. Currently Director of Marketing at <a href="http://evelo.com" class="bio-link">EVELO</a>. Built 2 startups with varying degrees of success that ultimately failed. <a href="http://brandery.org" class="bio-link">Brandery</a> mentor & alumn.</p>
  <p>I enjoy coffee <i class="em em-coffee"></i>, football <i class="em em-soccer"></i>, beer <i class="em em-beer"></i>, <%= link_to "flying", cities_path, :class => 'bio-link' %>  <i class="em em-airplane"></i> and <%= link_to "books", books_path, :class => 'bio-link' %> <i class="em em-books"></i>.</p>
    <br />
  <p><a href="https://m.gonsanchezs.com" class="bio-link">Read my blog on Medium</a> or <a href='mailto:gonsanchezs@gmail.com?Subject=Hello!"' class="bio-link">contact me</a>.</p>
</div>

<script>
var texts = ["marketer", "developer", "designer"];
var count = 0;
function changeText() {
    $(".skills").text(texts[count]);
    count < 4 ? count++ : count = 0;
}
setInterval(changeText, 1500);
</script>